# Generated by Django 5.0.3 on 2024-05-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='variation_value',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
